[Simulation Parameters]
WorldWidth=100
WorldHeight=100
InitialPreyCount=25
InitialPredatorCount=8
PreyStartingEnergy=50
PredatorStartingEnergy=60
MutationRate=0.1
InitialFoodCount=60
FoodRegenerationRate=3
FoodNutritionValue=10
MaxFoodCount=150
DeltaTime=1
;These two paramters are not really relevant in a visual representation
MaxSteps=100
OutputInterval=5